# Base configs
baseurl: ""
url: "http://photography.karanthukral.me"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Karan Thukral"
subtitle: "Aspiring Photographer"
author: "Karan Thukral"
bio: "I am a production engineer @ Shopify in Ottawa, Canada. Apart from tech I am an aspiring photographer!"
publicise: ""
web_design: ""
social_urls:
  twitter: "https://www.twitter.com/k_thukral"
  instagram: "https://www.instagram.com/kthukral"
  linkedin: "https://www.linkedin.com/in/thukralk"
  github: "https://www.github.com/karanthukral" 
